# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pippozord/Scrivania/nabto-client-edge-tunnel-1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pippozord/Scrivania/nabto-client-edge-tunnel-1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pippozord/Scrivania/nabto-client-edge-tunnel-1/CMakeFiles /home/pippozord/Scrivania/nabto-client-edge-tunnel-1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pippozord/Scrivania/nabto-client-edge-tunnel-1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GENERATE_VERSION

# Build rule for target.
GENERATE_VERSION: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GENERATE_VERSION
.PHONY : GENERATE_VERSION

# fast build rule for target.
GENERATE_VERSION/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GENERATE_VERSION.dir/build.make CMakeFiles/GENERATE_VERSION.dir/build
.PHONY : GENERATE_VERSION/fast

#=============================================================================
# Target rules for targets named edge_tunnel_client

# Build rule for target.
edge_tunnel_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 edge_tunnel_client
.PHONY : edge_tunnel_client

# fast build rule for target.
edge_tunnel_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/build
.PHONY : edge_tunnel_client/fast

#=============================================================================
# Target rules for targets named edge_tunnel_client_autogen_timestamp_deps

# Build rule for target.
edge_tunnel_client_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 edge_tunnel_client_autogen_timestamp_deps
.PHONY : edge_tunnel_client_autogen_timestamp_deps

# fast build rule for target.
edge_tunnel_client_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client_autogen_timestamp_deps.dir/build.make CMakeFiles/edge_tunnel_client_autogen_timestamp_deps.dir/build
.PHONY : edge_tunnel_client_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named edge_tunnel_client_autogen

# Build rule for target.
edge_tunnel_client_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 edge_tunnel_client_autogen
.PHONY : edge_tunnel_client_autogen

# fast build rule for target.
edge_tunnel_client_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client_autogen.dir/build.make CMakeFiles/edge_tunnel_client_autogen.dir/build
.PHONY : edge_tunnel_client_autogen/fast

#=============================================================================
# Target rules for targets named cpp_wrapper

# Build rule for target.
cpp_wrapper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpp_wrapper
.PHONY : cpp_wrapper

# fast build rule for target.
cpp_wrapper/fast:
	$(MAKE) $(MAKESILENT) -f nabto_cpp_wrapper/CMakeFiles/cpp_wrapper.dir/build.make nabto_cpp_wrapper/CMakeFiles/cpp_wrapper.dir/build
.PHONY : cpp_wrapper/fast

#=============================================================================
# Target rules for targets named cpp_wrapper_autogen_timestamp_deps

# Build rule for target.
cpp_wrapper_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpp_wrapper_autogen_timestamp_deps
.PHONY : cpp_wrapper_autogen_timestamp_deps

# fast build rule for target.
cpp_wrapper_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f nabto_cpp_wrapper/CMakeFiles/cpp_wrapper_autogen_timestamp_deps.dir/build.make nabto_cpp_wrapper/CMakeFiles/cpp_wrapper_autogen_timestamp_deps.dir/build
.PHONY : cpp_wrapper_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named cpp_wrapper_autogen

# Build rule for target.
cpp_wrapper_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpp_wrapper_autogen
.PHONY : cpp_wrapper_autogen

# fast build rule for target.
cpp_wrapper_autogen/fast:
	$(MAKE) $(MAKESILENT) -f nabto_cpp_wrapper/CMakeFiles/cpp_wrapper_autogen.dir/build.make nabto_cpp_wrapper/CMakeFiles/cpp_wrapper_autogen.dir/build
.PHONY : cpp_wrapper_autogen/fast

edge_tunnel_client_autogen/mocs_compilation.o: edge_tunnel_client_autogen/mocs_compilation.cpp.o
.PHONY : edge_tunnel_client_autogen/mocs_compilation.o

# target to build an object file
edge_tunnel_client_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/edge_tunnel_client_autogen/mocs_compilation.cpp.o
.PHONY : edge_tunnel_client_autogen/mocs_compilation.cpp.o

edge_tunnel_client_autogen/mocs_compilation.i: edge_tunnel_client_autogen/mocs_compilation.cpp.i
.PHONY : edge_tunnel_client_autogen/mocs_compilation.i

# target to preprocess a source file
edge_tunnel_client_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/edge_tunnel_client_autogen/mocs_compilation.cpp.i
.PHONY : edge_tunnel_client_autogen/mocs_compilation.cpp.i

edge_tunnel_client_autogen/mocs_compilation.s: edge_tunnel_client_autogen/mocs_compilation.cpp.s
.PHONY : edge_tunnel_client_autogen/mocs_compilation.s

# target to generate assembly for a file
edge_tunnel_client_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/edge_tunnel_client_autogen/mocs_compilation.cpp.s
.PHONY : edge_tunnel_client_autogen/mocs_compilation.cpp.s

src/MainWindow.o: src/MainWindow.cpp.o
.PHONY : src/MainWindow.o

# target to build an object file
src/MainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/src/MainWindow.cpp.o
.PHONY : src/MainWindow.cpp.o

src/MainWindow.i: src/MainWindow.cpp.i
.PHONY : src/MainWindow.i

# target to preprocess a source file
src/MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/src/MainWindow.cpp.i
.PHONY : src/MainWindow.cpp.i

src/MainWindow.s: src/MainWindow.cpp.s
.PHONY : src/MainWindow.s

# target to generate assembly for a file
src/MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/src/MainWindow.cpp.s
.PHONY : src/MainWindow.cpp.s

src/config.o: src/config.cpp.o
.PHONY : src/config.o

# target to build an object file
src/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/src/config.cpp.o
.PHONY : src/config.cpp.o

src/config.i: src/config.cpp.i
.PHONY : src/config.i

# target to preprocess a source file
src/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/src/config.cpp.i
.PHONY : src/config.cpp.i

src/config.s: src/config.cpp.s
.PHONY : src/config.s

# target to generate assembly for a file
src/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/src/config.cpp.s
.PHONY : src/config.cpp.s

src/edge_tunnel.o: src/edge_tunnel.cpp.o
.PHONY : src/edge_tunnel.o

# target to build an object file
src/edge_tunnel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/src/edge_tunnel.cpp.o
.PHONY : src/edge_tunnel.cpp.o

src/edge_tunnel.i: src/edge_tunnel.cpp.i
.PHONY : src/edge_tunnel.i

# target to preprocess a source file
src/edge_tunnel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/src/edge_tunnel.cpp.i
.PHONY : src/edge_tunnel.cpp.i

src/edge_tunnel.s: src/edge_tunnel.cpp.s
.PHONY : src/edge_tunnel.s

# target to generate assembly for a file
src/edge_tunnel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/src/edge_tunnel.cpp.s
.PHONY : src/edge_tunnel.cpp.s

src/iam.o: src/iam.cpp.o
.PHONY : src/iam.o

# target to build an object file
src/iam.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/src/iam.cpp.o
.PHONY : src/iam.cpp.o

src/iam.i: src/iam.cpp.i
.PHONY : src/iam.i

# target to preprocess a source file
src/iam.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/src/iam.cpp.i
.PHONY : src/iam.cpp.i

src/iam.s: src/iam.cpp.s
.PHONY : src/iam.s

# target to generate assembly for a file
src/iam.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/src/iam.cpp.s
.PHONY : src/iam.cpp.s

src/iam_interactive.o: src/iam_interactive.cpp.o
.PHONY : src/iam_interactive.o

# target to build an object file
src/iam_interactive.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/src/iam_interactive.cpp.o
.PHONY : src/iam_interactive.cpp.o

src/iam_interactive.i: src/iam_interactive.cpp.i
.PHONY : src/iam_interactive.i

# target to preprocess a source file
src/iam_interactive.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/src/iam_interactive.cpp.i
.PHONY : src/iam_interactive.cpp.i

src/iam_interactive.s: src/iam_interactive.cpp.s
.PHONY : src/iam_interactive.s

# target to generate assembly for a file
src/iam_interactive.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/src/iam_interactive.cpp.s
.PHONY : src/iam_interactive.cpp.s

src/pairing.o: src/pairing.cpp.o
.PHONY : src/pairing.o

# target to build an object file
src/pairing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/src/pairing.cpp.o
.PHONY : src/pairing.cpp.o

src/pairing.i: src/pairing.cpp.i
.PHONY : src/pairing.i

# target to preprocess a source file
src/pairing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/src/pairing.cpp.i
.PHONY : src/pairing.cpp.i

src/pairing.s: src/pairing.cpp.s
.PHONY : src/pairing.s

# target to generate assembly for a file
src/pairing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/src/pairing.cpp.s
.PHONY : src/pairing.cpp.s

src/timestamp.o: src/timestamp.cpp.o
.PHONY : src/timestamp.o

# target to build an object file
src/timestamp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/src/timestamp.cpp.o
.PHONY : src/timestamp.cpp.o

src/timestamp.i: src/timestamp.cpp.i
.PHONY : src/timestamp.i

# target to preprocess a source file
src/timestamp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/src/timestamp.cpp.i
.PHONY : src/timestamp.cpp.i

src/timestamp.s: src/timestamp.cpp.s
.PHONY : src/timestamp.s

# target to generate assembly for a file
src/timestamp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/src/timestamp.cpp.s
.PHONY : src/timestamp.cpp.s

src/version.o: src/version.cpp.o
.PHONY : src/version.o

# target to build an object file
src/version.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/src/version.cpp.o
.PHONY : src/version.cpp.o

src/version.i: src/version.cpp.i
.PHONY : src/version.i

# target to preprocess a source file
src/version.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/src/version.cpp.i
.PHONY : src/version.cpp.i

src/version.s: src/version.cpp.s
.PHONY : src/version.s

# target to generate assembly for a file
src/version.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_tunnel_client.dir/build.make CMakeFiles/edge_tunnel_client.dir/src/version.cpp.s
.PHONY : src/version.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... GENERATE_VERSION"
	@echo "... cpp_wrapper_autogen"
	@echo "... cpp_wrapper_autogen_timestamp_deps"
	@echo "... edge_tunnel_client_autogen"
	@echo "... edge_tunnel_client_autogen_timestamp_deps"
	@echo "... cpp_wrapper"
	@echo "... edge_tunnel_client"
	@echo "... edge_tunnel_client_autogen/mocs_compilation.o"
	@echo "... edge_tunnel_client_autogen/mocs_compilation.i"
	@echo "... edge_tunnel_client_autogen/mocs_compilation.s"
	@echo "... src/MainWindow.o"
	@echo "... src/MainWindow.i"
	@echo "... src/MainWindow.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/edge_tunnel.o"
	@echo "... src/edge_tunnel.i"
	@echo "... src/edge_tunnel.s"
	@echo "... src/iam.o"
	@echo "... src/iam.i"
	@echo "... src/iam.s"
	@echo "... src/iam_interactive.o"
	@echo "... src/iam_interactive.i"
	@echo "... src/iam_interactive.s"
	@echo "... src/pairing.o"
	@echo "... src/pairing.i"
	@echo "... src/pairing.s"
	@echo "... src/timestamp.o"
	@echo "... src/timestamp.i"
	@echo "... src/timestamp.s"
	@echo "... src/version.o"
	@echo "... src/version.i"
	@echo "... src/version.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

