name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04, macos-10.15]
    
    steps:
      - uses: actions/checkout@v2

      - name: Configure cmake
        run: mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/artifact ..

      - name: Build
        run: cmake --build build --target install

      - if: matrix.os == 'windows-2019'
        name: Test run
        run: ${{ github.workspace }}/artifact/edge_tunnel_client.exe

      - if: matrix.os != 'windows-2019'
        name: Test run
        run: ${{ github.workspace }}/artifact/edge_tunnel_client

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.runner.os }}-artifact
          path: ${{ github.workspace }}/artifact/

  release-artifacts:
    name: Release Step
    needs: build
    runs-on: ubuntu-18.04

    # if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: ${{ github.workspace }}/artifacts
      - run: ls -R ${{ github.workspace }}/artifacts
