name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      - name: Configure cmake
        run: mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/artifact ..

      - name: Build
        run: cmake --build build --target install

      - if: matrix.os == 'windows-2019'
        name: Test run
        run: ${{ github.workspace }}/artifact/edge_tunnel_client.exe

      - if: matrix.os != 'windows-2019'
        name: Test run
        run: ${{ github.workspace }}/artifact/edge_tunnel_client

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-artifact
          path: ${{ github.workspace }}/artifact/

  release-assets:
    name: Release Assets
    needs: build
    runs-on: ubuntu-18.04

    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: ${{ github.workspace }}/artifacts
      - name: Make asset files
        run: |
          cd ${{ github.workspace }}/artifacts

          mv Linux-artifact edge_tunnel_client
          tar -czf ${{ github.workspace }}/artifacts/edge_tunnel_client-linux.tar.gz edge_tunnel_client
          rm -r edge_tunnel_client

          mv Windows-artifact edge_tunnel_client
          zip -r ${{ github.workspace }}/artifacts/edge_tunnel_client-windows.zip edge_tunnel_client
          rm  -r edge_tunnel_client

          mv macOS-artifact edge_tunnel_client
          zip -czf ${{ github.workspace }}/artifacts/edge_tunnel_client-macos.tar.gz edge_tunnel_client
          rm -r edge_tunnel_client

      - name: Upload Linux asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.workspace }}/artifacts/edge_tunnel_client-linux.tar.gz
          asset_name: edge_tunnel_client-linux.tar.gz
          asset_content_type: application/gzip
      - name: Upload Windows asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.workspace }}/artifacts/edge_tunnel_client-windows.zip
          asset_name: edge_tunnel_client-windows.zip
          asset_content_type: application/zip
      - name: Upload MacOS asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.workspace }}/artifacts/edge_tunnel_client-macos.tar.gz
          asset_name: edge_tunnel_client-macos.tar.gz
          asset_content_type: application/gzip
