name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    name: Windows Build
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Configure cmake
        run: mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=$env:HOME/install ..
      - name: Build
        run: cmake --build build --target install
      - name: Test run
        run: $env:HOME/install/edge_tunnel_client.exe

  build-linux:
    name: Linux Build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Configure cmake
        run: mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=$HOME/install ..
      - name: Build
        run: cmake --build build --target install
      - name: Test run
        run: $HOME/install/edge_tunnel_client
