name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    name: Windows Build
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Configure cmake
        run: mkdir build && cd build && cmake ..
      - name: Build
        run: cmake --build build
